import React, { FC } from 'react'
import Head from 'next/head'
import Header from './Header'

const Layout: FC<{}> = ({ children }) => {
    return (
        <>
            <Head>
                <title>Organic</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div>
                <Header />
                <main className="mycontainer">
                    {children}
                </main>
            </div>
        </>
    )
}

export default Layout
