import type { NextPage } from 'next'
import Head from 'next/head'
import Typography from '../components/typography/Typography'


const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Organic</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     <div>
      
     </div>
    </div>
  )
}

export default Home
